// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGroCosI5BrdH9Of_oZvAq0ycxPVdWJv4',
    appId: '1:483071714296:web:4fcea656d2fbf94e8fac0d',
    messagingSenderId: '483071714296',
    projectId: 'flutter-study-todo',
    authDomain: 'flutter-study-todo.firebaseapp.com',
    storageBucket: 'flutter-study-todo.appspot.com',
    measurementId: 'G-MGXYR2GWS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB668RHStZKSrNafsGJDfIb5M9kQPmjexQ',
    appId: '1:483071714296:android:e1c1191cf20afda28fac0d',
    messagingSenderId: '483071714296',
    projectId: 'flutter-study-todo',
    storageBucket: 'flutter-study-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMyjNC5VAhyxoj6sF6O8_C9aOUue4kYGk',
    appId: '1:483071714296:ios:8722fcd9431cc7138fac0d',
    messagingSenderId: '483071714296',
    projectId: 'flutter-study-todo',
    storageBucket: 'flutter-study-todo.appspot.com',
    iosClientId: '483071714296-st7j8kcfpej1omaof6nlusu4thb24iab.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMyjNC5VAhyxoj6sF6O8_C9aOUue4kYGk',
    appId: '1:483071714296:ios:8722fcd9431cc7138fac0d',
    messagingSenderId: '483071714296',
    projectId: 'flutter-study-todo',
    storageBucket: 'flutter-study-todo.appspot.com',
    iosClientId: '483071714296-st7j8kcfpej1omaof6nlusu4thb24iab.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodo',
  );
}
